name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Load FNM
            export PATH="/home/${{ secrets.SERVER_USER }}/.local/share/fnm:$PATH"
            eval "`fnm env --use-on-cd`"
            
            # Navigate to project directory
            cd /var/www/helpdesk
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            npm install --production
            
            # Start/Restart PM2
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
            pm2 save
